/*
 * @rpi1337
 */

const NOTIFICATION_TYPE = {
	'GROUP_INVITATION'				:'GROUP_INVITATION',
	'GROUP_INVITATION_ACCEPTED'		:'GROUP_INVITATION_ACCEPTED',
	'GROUP_JOIN_REQUEST'			:'GROUP_JOIN_REQUEST', // TODO
	'GROUP_JOIN_REQUEST_ACCEPTED'	:'GROUP_JOIN_REQUEST_ACCEPTED', // TODO
	'GROUP_POST_REQUEST'			:'GROUP_POST_REQUEST', // TODO
	'GROUP_POST_REQUEST_ACCEPTED'	:'GROUP_POST_REQUEST_ACCEPTED', // TODO
	'POST_LIKE'						:'POST_LIKE',
	'POST_LIKE_MULTI'				:'POST_LIKE_MULTI',
	'POST_COMMENT'					:'POST_COMMENT',
	'POST_COMMENT_MULTI'			:'POST_COMMENT_MULTI',
	'FRIEND_REQUEST'				:'FRIEND_REQUEST',
	'STARTED_FOLLOWING'				:'STARTED_FOLLOWING',
	'STARTED_FOLLOWING_MULTI'		:'STARTED_FOLLOWING_MULTI',
	'PLATFORM_INVITATION_ACCEPTED'	:'PLATFORM_INVITATION_ACCEPTED',
	'NEW_MESSAGE'					:'NEW_MESSAGE'
};

export default NOTIFICATION_TYPE;